name: CI

env:
  OTP_VERSION: 26.1.2
  ELIXIR_VERSION: 1.15.7

# based https://github.com/erlef/setup-beam

on:
  push:
    branches:
      - 'pojiro/0.2.0-dev'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{env.OTP_VERSION}}
          elixir-version: ${{env.ELIXIR_VERSION}}

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: get deps
        run: mix do deps.get, deps.compile

      - name: format
        run: mix format --check-formatted

      - name: cargo fmt
        working-directory: native/zenohex_nif
        run: cargo fmt --all -- --check

      - name: test & coverage
        run: |
          mix test --warnings-as-errors
          mix test --cover

      - name: credo
        run: mix credo --all
